### ISSUE TITLE
Using a Different Set of Data Pairs

### ISSUE THREAD

**Issue by renxinyang** [DirtyHarryLYL/SymNet#5]
Dear authors,

Thanks a lot for the brillant repo! As I understand, currently the repo is limited to the train and test pairs provided in compositional-split, primarily due to the utils/aux_data/UT_weight.py file (using UT as an example). Is it possible to evaluate the model on custom-defined train_pairs.txt and test_pairs.txt? Thanks a lot!

**Comment by silicx** [comment]
Take UT as example:

- If you are using customized pairs composed by the provided attributes and objects, only the pair lists in `data/ut-zap50k-original/compositional-split/` need to be updated.

- If you also use customized attributes and objects, there are several additional files to modify in folder `utils/aux_data/`:

  1. `UT_attrs.json` and `UT_objs.json` are attribute and object list, stored as dict. The keys are original names and values are names in pre-trained GloVe vocabs.
  2. `glove_UT.py` contains GloVe vectors for attributes and objects.
  3. `UT_weight.py` contains loss weights for each individual attribute or object class (`attr_weight` and `obj_weight`). In practice, these weights can help the training on imbalanced data. Each weight is computed by _-log(p)_, where _p_ is the occurrence frequency of an attribute or object **in train set**. You may clip the values to prevent large or zero weights.

**Comment by renxinyang** [comment]
Thanks a lot for the quick response! Your answers have already sufficiently answered my questions, but just in order to confirm my understanding is correct---

For i and ii, we would look at the proper Glove embeddings and obtain the correponding values. For this paper, I believe glove.6B.300d.txt is used?

For iii, we would count the frequency of each word, and do -log(). Using attributes as an example, say we have only two attributes and each appeared in the training set once. Then, the attr_weight vector is a two-dimensional vector with entries [log(2), log(2)].

Could you kindly confirm my understanding is correct? Thanks again for the incredibly helpful answers!

**Comment by silicx** [comment]
Yes, they are all correct, including the GloVe vectors we use.

**Comment by renxinyang** [comment]
Hi Silicx,

Apologies for opening this issue again. As I was doing the UT_weight.py calculations, I noticed that there was likely a misunderstanding on my part. Following the example I used in my previous thread, wouldn't the pair_weights all be the same, since each pair appeared in train_pairs.txt exactly once? In addition, the length of the provided pair_weights list doesn't match the total number of train_pairs in train_pairs.txt. Do you mind elaborating on this part a bit more? Thanks a lot!

**Comment by silicx** [comment]
Maybe you misunderstand the _frequency_ of an attribute or object class, which is [number of **samples** in this class] divided by [total number of samples]. E.g., if a training set with 2 object classes {a, b} and 5 images is labeled {a, a, a, b, b}, the frequencies of objects are 0.6 and 0.4, and obj_weight={-log0.6, -log0.4}.

The pair_weight is not used in our model since there is no pair-specific loss. And it is also unsuitable for CZSL task due to the unseen pairs in test set. You may leave it blank.

**Comment by QiyaoWei** [comment]
Dear authors,

I am currently reproducing the code with custom-defined datasets, and is running into similar problems. Specifically, I believe the file utils/aux_data/UT_gamma.json needs to be modified as well. I have modified everything as per the discussion above, but training symnet gave me the following error. It would be great if the authors could clarify this---

C:\Users\administered\anaconda3\envs\adj\python.exe E:/wqy/SymNet-master/run_symnet.py --name UT_best --data UT --epoch 700 --obj_pred UT_obj_lr1e-3_test_ep300.pkl --batchnorm --wordvec onehot --lr 1e-4 --bz 256 --lambda_cls_attr 1 --lambda_cls_obj 0.5 --lambda_trip 0.5 --lambda_sym 0.01 --lambda_axiom 0.03
[2021-03-26 10:48:36,427] MAIN: Name:       UT_best
[2021-03-26 10:48:36,427] MAIN: Network:    symnet
[2021-03-26 10:48:36,427] MAIN: Data:       UT
[2021-03-26 10:48:36,427] MAIN: FC layers:  At [512], Cm [768], Cls [512]
[2021-03-26 10:48:36,427] MAIN: Loading dataset
30496 activations loaded
#images = 8123
30496 activations loaded
#images = 2098
Loading object prediction from obj_scores\UT_obj_lr1e-3_test_ep300.pkl
[2021-03-26 10:48:36,769] MAIN: Loading network and solver
[2021-03-26 10:48:37,529] tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

[2021-03-26 10:48:37,530] tensorflow: From E:\wqy\SymNet-master\network\symnet.py:24: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

[2021-03-26 10:48:37,534] tensorflow: From E:\wqy\SymNet-master\utils\utils.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

[2021-03-26 10:48:37,534] tensorflow: From E:\wqy\SymNet-master\utils\utils.py:18: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

[2021-03-26 10:48:37,672] solver.init: training weight  => ./weights/UT_best
[2021-03-26 10:48:37,672] solver.init: training log     => ./logs/UT_best
[2021-03-26 10:48:37,673] solver.train_model: Begin training
[2021-03-26 10:48:37,677] tensorflow: From E:\wqy\SymNet-master\network\base_network.py:78: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

[2021-03-26 10:48:37,677] tensorflow: From E:\wqy\SymNet-master\network\base_network.py:87: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

[2021-03-26 10:48:37,678] tensorflow: From C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py:1866: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
[2021-03-26 10:48:38,032] tensorflow: From E:\wqy\SymNet-master\network\base_network.py:112: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
[2021-03-26 10:48:38,032] tensorflow: From E:\wqy\SymNet-master\network\base_network.py:116: The name tf.log is deprecated. Please use tf.math.log instead.

[2021-03-26 10:48:38,187] tensorflow: From E:\wqy\SymNet-master\network\symnet.py:197: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

Traceback (most recent call last):
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 16 and 21 for 'mul_7' (op: 'Mul') with input shapes: [16], [?,21].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wqy/SymNet-master/run_symnet.py", line 371, in <module>
    main()
  File "E:/wqy/SymNet-master/run_symnet.py", line 170, in main
    sw.trainval_model(sess, args.epoch)
  File "E:/wqy/SymNet-master/run_symnet.py", line 262, in trainval_model
    lr, score_op, train_op, train_summary_op = self.construct_graph(sess)
  File "E:/wqy/SymNet-master/run_symnet.py", line 227, in construct_graph
    loss_op, score_op, train_summary_op = self.network.build_network()
  File "E:\wqy\SymNet-master\network\symnet.py", line 317, in build_network
    repeat_img_feat, is_training=False, metric='rmd')
  File "E:\wqy\SymNet-master\network\symnet.py", line 108, in RMD_prob
    d_plus_comp  = self.dset.comp_gamma['b']*d_plus
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 925, in r_binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 6701, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1770, in __init__
    control_input_ops)
  File "C:\Users\administered\anaconda3\envs\adj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 16 and 21 for 'mul_7' (op: 'Mul') with input shapes: [16], [?,21].

Process finished with exit code 1

**Comment by silicx** [comment]
"UT_gamma" is weight in RMD and is only used in CZSL setting (not used in GCZSL and CAUSAL). You may set each components of "UT_gamma" to 1 to disable RMD weighting, which may leads to slight performance drop but can be compensated by carefully tuning the hyperparameters. We will clarify this weight as well as the dataset customization process in README.
For our model, we split 30% of the train set as our validation set and obtain the RMD weight by grid-search on the valid set.
